config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vn/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/about", to: "static_pages#about"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only:  %i(new create show)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: Settings.model.user.name.lenght}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: Settings.model.user.email.lenght},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { maximum: Settings.model.user.password.lenght}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false unless remember_digest

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update remember_digest: nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  include SessionsHelper

  private

  def default_url_options
    {locale: I18n.locale }
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale.to_sym : nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user&.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == "1" ? remember(@user) : forget(@user)
      flash[:success] = t "users.success"
      redirect_to user_path id: @user.id
    else
      flash.now[:danger] = t "login.fail"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def contact; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
    return if @user

    flash[:warning] = t "users.user_nil"
    redirect_to action: :new
  end

  def create
    @user = User.new(user_params)
    return render:new unless @user.save

    log_in @user
    flash[:success] = t "users.success"
    redirect_to user_path id: @user.id
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title page_title
    base_title = I18n.t "static_pages.base_title"
    page_title.blank? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://www.railstutorial.org/"><%= t "static_pages.base_title" %></a>
    <%= t "static_pages.by" %> <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t( "static_pages.about"), about_path %></li>
      <li><%= link_to t( "static_pages.contact"), contact_path %></li>
      <li><a href="https://news.railstutorial.org/"><%= t "static_pages.news" %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t( "static_pages.home"), root_path %></li>
        <li><%= link_to t( "static_pages.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t( "users.user"), "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "users.acc" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t( "users.pro"), current_user %></li>
              <li><%= link_to t( "users.set"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t( "users.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t( "static_pages.login"), login_path %></li>
        <% end %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <%= t "static_pages.language" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t( "static_pages.eng"), locale: :en %></li>
            <li><%= link_to t( "static_pages.vie"), locale: :vn %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "users.error" %><%= pluralize(@user.errors.count, t( "users.errors")) %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1><%= t "static_pages.about" %></h1>
<p>
  <%= t "static_pages.base_title" %>,
  <%= t "about.paragraph_1" %> <a href="">Learn Enough</a>,
  <%= t "about.paragraph_5" %> <a href=""><%= t "about.book" %></a>
  <%= t "about.and" %><a href="">
  <%= t "about.paragraph_6" %></a> <%= t "about.paragraph_3" %>
  <a href="">Ruby on Rails</a>. <%= t "about.paragraph_4" %>.
</p>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1><%= t "static_pages.contact" %></h1>
<p>
  <%= t "contact.paragraph_1" %>
  <a href="https://www.railstutorial.org/contact"><%= t "contact.page" %></a>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1><%= t "static_pages.help" %></h1>
<p>
  <%= t "help.paragraph_1" %>
  <a href="https://www.railstutorial.org/help"><%= t "help.page" %></a>.
  <%= t "help.paragraph_2" %>
  <a href="https://www.railstutorial.org/book"><em><%= t "static_pages.base_title" %></em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide :title, "Home" %>
<div class="center jumbotron">
  <h1><%= t "home.welcome" %></h1>
  <h2><%= t "home.p1" %>
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    <%= t "home.p2" %>
  </h2>
  <div class="btn btn-lg btn-success">
    <%= link_to t( "home.signup"), signup_path %>
  </div>
</div>
<%= link_to image_tag("https://rubyonrails.org/images/rails-logo.svg", alt: "Rails logo", width: "200px"),
"https://rubyonrails.org/" %>

app/views/users/new.html.erb
<% provide :title, "Sign Up" %>
<center><h1><%= t "users.signup" %></h1></center>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user , url: signup_path do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name, t( "users.name") %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password, t( "users.password")%>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, t( "users.confirm_password") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t( "users.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>